[package]
name = "tree_stump"
version = "0.1.0"
edition = "2021"
authors = ["joker1007 <kakyoin.hierophant@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { git = "https://github.com/pboling/magnus.git", rev = "93960fa00b5949a2a977f282e3f58b522b13a77e" }
rb-sys = { version = "0.9.124", features = ["stable-api-compiled-fallback"] }
tree-sitter = "0.26"
tree-sitter-language = "0.1"
libloading = "~0.8.4"
streaming-iterator = "0.1"
